export const USER_TOKEN_ID_RECEIVED = 'USER_TOKEN_ID_RECEIVED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const MEMBERS_RECEIVE = 'MEMBERS_RECEIVE';
export const MEMBERS_RECEIVE_SUCCESS = 'MEMBERS_RECEIVE_SUCCESS';
export const MEMBERS_RECEIVE_ERROR = 'MEMBERS_RECEIVE_ERROR';